name: 機能改善・要望
description: 新機能の提案やプロジェクトの改善要望
title: "[FEATURE] "
labels: ["enhancement"]
assignees:
  - []
body:
  - type: checkboxes
    id: feature_type
    attributes:
      label: 改善・要望の種類
      description: 該当する種類を選択してください（複数選択可）
      options:
        - label: 新機能の追加
        - label: 既存機能の改善
        - label: パフォーマンス向上
        - label: ドキュメント改善
        - label: 開発環境・ツール改善
        - label: CI/CD・自動化改善
        - label: テスト改善
        - label: コード品質向上

  - type: textarea
    id: problem_statement
    attributes:
      label: 現在の問題・課題
      description: 現在どのような問題や不便さがあるかを説明してください
      placeholder: |
        - 何が問題なのか
        - どのような不便さがあるのか
        - 現在の制限事項
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: 提案する解決策
      description: どのような機能や改善を提案するかを詳しく説明してください
      placeholder: |
        - 具体的な実装案
        - 期待される動作
        - 技術的なアプローチ
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: 利用シーン・用途
      description: この機能がどのような場面で役立つかを説明してください
      placeholder: |
        - どのような場面で使用するか
        - 誰にとって有用か
        - どの程度の頻度で使用されるか
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案・検討事項
      description: 他に考えられる実装方法や関連する課題があれば記載してください
      placeholder: |
        - 他の実装方法
        - 技術的な制約
        - 影響を受ける他の機能
        - 互換性の考慮事項
    validations:
      required: false

  - type: checkboxes
    id: related_areas
    attributes:
      label: 関連する技術領域
      description: この要望に関連する技術領域を選択してください（複数選択可）
      options:
        - label: アルゴリズム実装
        - label: 数学・数論
        - label: パフォーマンス最適化
        - label: テスト自動化
        - label: ドキュメント生成
        - label: コード品質ツール
        - label: CI/CDパイプライン
        - label: 開発環境
        - label: セキュリティ

  - type: textarea
    id: additional_context
    attributes:
      label: 追加情報・参考資料
      description: 参考になるリンク、類似の実装例、関連するIssueなどがあれば記載してください
      placeholder: |
        - 参考URL
        - 類似プロジェクトの実装例
        - 関連するGitHub Issue
        - その他の参考情報
    validations:
      required: false
