name: 新しいProject Euler問題の実装
description: 新しいProject Euler問題の解法実装を追加する
title: "Solve Problem [PROBLEM_NUMBER]: [PROBLEM_TITLE]"
labels: ["problem", "in-progress"]
assignees:
  - []
body:
  - type: input
    id: problem_number
    attributes:
      label: 問題番号
      description: Project Eulerの問題番号を入力してください
      placeholder: "例: 008"
    validations:
      required: true

  - type: input
    id: problem_title
    attributes:
      label: 問題タイトル
      description: Project Eulerの問題タイトルを入力してください
      placeholder: "例: Largest product in a series"
    validations:
      required: true

  - type: input
    id: problem_url
    attributes:
      label: 問題URL
      description: Project Euler公式サイトの問題URLを入力してください
      placeholder: "https://projecteuler.net/problem=xxx"
    validations:
      required: true

  - type: textarea
    id: problem_description
    attributes:
      label: 問題概要
      description: 問題の簡潔な説明を記載してください
      placeholder: |
        問題の内容を簡潔に説明してください。
        具体的な数値例や制約条件も含めると良いでしょう。
    validations:
      required: true

  - type: checkboxes
    id: approaches
    attributes:
      label: 実装予定のアプローチ
      description: 実装予定のアプローチにチェックを入れてください（複数選択可）
      options:
        - label: 素直な解法 (solve_naive) - O(n)の実装
          required: true
        - label: 最適化解法 (solve_optimized) - O(log n)やO(1)の実装
          required: false
        - label: 数学的解法 (solve_mathematical) - 数式ベースの実装
          required: false

  - type: checkboxes
    id: tasks
    attributes:
      label: 実装チェックリスト
      description: 以下のタスクを順次実行してください（リファクタ後の構造に対応）
      options:
        - label: アルゴリズム関数の実装 (problems/problem_XXX.py) - 純粋なアルゴリズムのみ
          required: false
        - label: 実行用ランナーの作成 (problems/runners/problem_XXX_runner.py) - テスト・実行・表示コード
          required: false
        - label: 包括的なテストの作成 (tests/problems/test_problem_XXX.py)
          required: false
        - label: 解法ドキュメントの作成 (docs/solutions/solution_XXX.md)
          required: false
        - label: 進捗追跡の更新 (PROGRESS.md)
          required: false
        - label: ランナー動作確認 (make run-problem PROBLEM=XXX)
          required: false
        - label: 個別テスト実行確認 (make test-problem PROBLEM=XXX)
          required: false
        - label: コード品質チェック (make quality)
          required: false
        - label: 全テスト実行確認 (make test)
          required: false
        - label: CI/CD確認（全てのチェックがSUCCESS）
          required: false
        - label: ブランチ作成 (gh issue develop [ISSUE_NUMBER])
          required: false
        - label: プルリクエスト作成
          required: false
        - label: CI完了待ち（全てのチェックがSUCCESS）
          required: false
        - label: CI状態確認 (gh pr view [PR_NUMBER] --json statusCheckRollup)
          required: false
        - label: プルリクエストマージ（CI成功確認後）
          required: false
        - label: イシュークローズ
          required: false
        - label: MkDocsドキュメントビルド確認 (make docs-strict)
          required: false
        - label: パフォーマンス分析実装確認（共有ユーティリティ使用）
          required: false

  - type: textarea
    id: notes
    attributes:
      label: 備考・参考情報
      description: アルゴリズムのヒント、参考資料、特記事項などがあれば記載してください
      placeholder: |
        ## 実装構造について（リファクタ後）
        - **problems/problem_XXX.py**: 純粋なアルゴリズム関数のみ（solve_naive, solve_optimized等）
        - **problems/runners/problem_XXX_runner.py**: 実行・テスト・表示用コード（共有ユーティリティ使用）
        - **problems/utils/performance.py**: パフォーマンス測定用共有ユーティリティ
        - **problems/utils/display.py**: 表示・フォーマット用共有ユーティリティ

        ## アルゴリズム・参考情報
        - 参考になるアルゴリズム
        - 数学的背景
        - 実装上の注意点
        - その他特記事項
    validations:
      required: false
